// C3: policy as a hook. A PreToolUse hook runs before the permission check and
// before any human sees the call, so a path on this list is denied even if
// somebody would have typed y.
import { isAbsolute, relative } from "node:path";
import type { HookCallback } from "@anthropic-ai/claude-agent-sdk";

const PROTECTED: { pattern: RegExp; why: string }[] = [
  { pattern: /^\.env/, why: "holds secrets" },
  { pattern: /^drizzle\//, why: "is generated by drizzle-kit" },
  { pattern: /^lib\/auth[^/]*\.ts$/, why: "is the authentication setup" },
  { pattern: /(^|\/)package\.json$/, why: "changes dependencies" },
];

export function protectedPaths(root: string): HookCallback {
  return async (input) => {
    if (input.hook_event_name !== "PreToolUse") return {};
    const toolInput = input.tool_input as { file_path?: string };
    if (!toolInput.file_path) return {};
    const path = isAbsolute(toolInput.file_path)
      ? relative(root, toolInput.file_path)
      : toolInput.file_path;
    const hit = PROTECTED.find((p) => p.pattern.test(path));
    if (!hit) return {};
    console.log(
      `   [hook] denied ${input.tool_name} on ${path}: it ${hit.why}`,
    );
    return {
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: `${path} ${hit.why}, so this program never changes it. Fix the finding somewhere else or explain why you cannot.`,
      },
    };
  };
}

// The tools that write files. The matcher is a regular expression.
export const WRITE_TOOLS = "Edit|Write|MultiEdit|NotebookEdit";
